import os
os.system("pkg install pip")
os.system("pip install telethon")
os.system("pip install aiocron")
os.system("pip install emoji")
os.system("pip install asyncio")
os.system("pip install datetime")
os.system("pip install base64")
os.system("pip install gpytranslate")
os.system("pip install pytz")
os.system("pip install gtts")
os.system("pip install qrcode")
os.system("clear")
